metavrse-inc/metavrse-lib

.github/workflows/.release-package.yml, package.json, src/index.d.ts, src/index.ts, tsconfig.json, webpack.config.js, yarn.lock
Add ability to obtain cherryGL package version so we can check it in application.
=> feat: MET-1782 add version from package.json

.gitignore, src/types/assets/AssetType.d.ts
Add video as AssetType - for video panel purposes
=> feat: MET-237 extend assetType model to video files

.github/workflows/.pull-request.yml, .github/workflows/.release-package.yml, dts.config.js, package.json, yarn.lock
Fix missing package.json when publishing package.
=> fix: MET-1888 fix missing package.json when publishing

dts.config.js, package.json, src/assets/scripts/ProjectManager/Scene/Object.js, src/assets/scripts/ProjectManager/Scenegraph.js, src/facade/index.ts, src/types/cherry/CherryProjectData.ts, src/types/configurations/Configuration.ts, src/types/configurations/ConfigurationType.ts, src/types/index.ts, src/types/project/old/OldAsset.ts, src/types/project/old/OldConfiguration.ts, src/types/project/old/OldProjectData.ts, src/types/project/old/OldTreeNode.ts
Fix issue with loading data from new structure. Added to rollup checking if env is development so
the assets are not minified for better sourcemaps. Added types and refactor some of them.
=> feat: MET-1716 change types and assets fixes

src/types/index.ts
add missing exports for Code Components
=> fix: MET-262 add missing exports

src/constants/index.ts, src/types/assets/AssetType.ts, src/types/configurations/ConfigurationType.ts, src/types/entities/Entity.ts, src/types/entities/HudHtmlEntity.ts, src/types/index.ts, src/types/project/old/OldAsset.ts, src/types/project/old/OldTreeNode.ts, src/types/tree/TreeNodeType.ts
This PR will add new types espesialy the HudHtmlEntity and types for the old structure.
=> feat: MET-1956 support for HTMLElement from old editor

package.json, src/assets/scripts/ProjectManager/Scene/Object.js, src/facade/index.ts, src/types/cherry/CherryProjectManager.ts, src/types/cherry/CherryProjectManagerObject.ts, src/types/facade/CherryFacade.ts, yarn.lock
fix: MET-1410 issue with resizing object when adding to scene
=> Feature/MET-1416 Add method addObjectToScene

src/types/animation/AnimationEventType.ts, src/types/cherry/CherryProjectManagerObject.ts
Will add missing type for animation event
=> fix: MET-2093 missing type for animation event

src/facade/index.ts, src/types/cherry/CherryObjectInfo.ts, src/types/cherry/CherrySurfaceSceneObject.ts, src/types/cherry/CherryViewerFileSystem.ts
This PR will implement getObjectInfo to show information in editor InfoPanel.
=> fix: MET-2102 add method to facade to read the object informations

src/facade/index.ts
Will add ability to update meshes based on type
=> feat: MET-236 add mesh type to setObjectMaterial method

src/facade/index.ts
This PR will add default value for texture channel when reading materials from cherryGL
=> fix: MET-226 add default value for texture channel

src/assets/scripts/ProjectManager/Scene/Camera.js
Part of the fix for: https://startuphouse.atlassian.net/browse/MET-2188
The problem was located in line 132
=> fix: MET-2188 allow to change the position of the camera

src/assets/scripts/main.js
=> fix: MET-2142 fix problem with preview on smaller screens

src/types/cherry/CherryProjectData.ts, src/types/cherry/CherryProjectManagerObject.ts, src/types/world/World.ts
Add world types and some fixes to types
=> fix: MET-2156 add world types and missing types

package.json
This commit will bump version to 1.0.0
=> chore: bump version to 1.0.0

package.json, src/constants/entities/worldDefaults.ts, src/constants/index.ts, src/facade/index.ts, src/index.ts, src/types/project/old/OldProjectData.ts, src/utils/regenerateStructure.util.ts, src/utils/restructureAssets.util.ts, src/utils/restructureConfigurations.util.ts, src/utils/restructureData.util.ts, yarn.lock
Will move method from frontend to the library
=> feat(utils): add restructure method

src/constants/gizmo.ts, src/constants/index.ts, src/facade/gizmo.ts, src/facade/gizmoHelpers/gizmo.ts, src/facade/gizmoHelpers/gizmoActions.ts, src/facade/gizmoHelpers/gizmoMove.ts, src/facade/gizmoHelpers/gizmoTextures.ts, src/facade/index.ts, src/types/entities/ObjectEntity.ts, src/types/gizmo/Gizmo.ts, src/types/index.ts
This PR adds helper methods from `metavrse-front` to facade in lib.
=> MET-1973: Editor - Light gizmo breaks when an object is selected

src/constants/entities/videoDefaults.ts, src/facade/index.ts, src/types/cherry/CherryProjectManagerObject.ts
In this PR I'm:
- adding missing properties for video component
- change default video properties, because previous was wrong
=> feature/MET-2478: Video component needs be draggable into albedo

src/assets/scripts/ProjectManager/Scenegraph.js, src/facade/index.ts
This PR will add configuration support so the cherryGL can read it
=> feat: MET-2525 add configuration support

src/facade/index.ts, src/facade/zoom.ts
Adding method in facade that is calculating position for zoom to object when pressing `f` key.
=> feature/MET-2539: Create zoom to an object shortcut

src/assets/scripts/ProjectManager/Scene/HTMLElement.js, src/assets/scripts/ProjectManager/Scene/World.js, src/types/htmlHud/HTMLHudNode.ts, src/utils/restructureData.util.ts
This PR restructures old projects HTML hud for new structure
=> MET-2497: Handle HTML HUD on project import

src/assets/scripts/ProjectManager/Scene/ObjectLink.js
Task: [MET-2264](https://startuphouse.atlassian.net/browse/MET-2264?atlOrigin=eyJpIjoiN2RlYzNiOTMwMDM5NGRhYzkxMDkzNDhhYWE5MTJmOTgiLCJwIjoiaiJ9)
=> feature/MET-2264: Configuration in Components panel

src/types/cherry/CherryProjectManagerObject.ts
Exported the function needed for the config mode changes, with the proper typings.
=> feat: AT-4 Export getProperties function for CherryProjectManagerObject

src/types/assets/Asset.ts
Also added filetype for the future so that sometime we might introduce proper file types for added assets.
=> feat: AT-36 Add intrinsics to Asset type
